/*
 * This source file was generated by the Gradle 'init' task
 */
package com.notmorexray;


import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

public class Main extends JavaPlugin {
    @Override
    public void onEnable() {
        getLogger().info("Plugin Anti-Xray ativado!");

        // ✅ Registrar evento de mineração suspeita
        Bukkit.getPluginManager().registerEvents(new XrayListener(this), this);
    }
    public String getGreeting() {
    return "Bem-vindo ao servidor!";
}

    @Override
    public void onDisable() {
        getLogger().info("Plugin Anti-Xray desativado!");
    }
}